#!/usr/bin/env ruby

l1 = []
l2 = []

ARGF.readlines.each.map(&:chomp).each {|l| _l,_r = l.split.map(&:to_i); l1 << _l; l2 << _r }

puts l1.sort.zip(l2.sort).map { |p| (p.first - p.last).abs }.sum # 1319616
