#!/usr/bin/env ruby

grid = ARGF.readlines.map(&:chomp)

sx = grid.first.size
sy = grid.size
mx = sx - 1
my = sy - 1

antennae = Hash.new { |h,k| h[k] = [] }
antinode = Hash.new { |h,k| h[k] = [] }

Coord = Struct.new(:x,:y)

sy.times do |y|
  sx.times do |x|
    antennae[grid[y][x]] << Coord.new(x,y) unless grid[y][x] == ?.
  end
end

antennae.each do |ant, positions|
  positions.permutation(2).each do |pair|
    dx = pair[1].x - pair[0].x
    dy = pair[1].y - pair[0].y

    anti = Coord.new(pair[0].x, pair[0].y)
    while anti.x.between?(0,mx) && anti.y.between?(0,my)
      antinode[ant] << anti.dup
      anti.x += dx ; anti.y += dy
    end
  end
end

puts antinode.values.flatten.uniq.size # 1308
